containerbank3/src/main/java/org/hackathon/packapp/containerbank/model/Advisor.java
package org.hackathon.packapp.containerbank.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;

import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;

/**
 * Simple JavaBean domain object representing an advisor.
 *
 * @author Wavestone
 */
@Entity
@Table(name = "advisors")
public class Advisor extends Person {

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "advisor_specialties", joinColumns = @JoinColumn(name = "advisor_id"),
        inverseJoinColumns = @JoinColumn(name = "specialty_id"))
    private Set<Specialty> specialties;

    protected Set<Specialty> getSpecialtiesInternal() {
        if (this.specialties == null) {
            this.specialties = new HashSet<>();
        }
        return this.specialties;
    }

    protected void setSpecialtiesInternal(Set<Specialty> specialties) {
        this.specialties = specialties;
    }

    @XmlElement
    public List<Specialty> getSpecialties() {
        List<Specialty> sortedSpecs = new ArrayList<>(getSpecialtiesInternal());
        PropertyComparator.sort(sortedSpecs, new MutableSortDefinition("name", true, true));
        return Collections.unmodifiableList(sortedSpecs);
    }

    public int getNrOfSpecialties() {
        return getSpecialtiesInternal().size();
    }

    public void addSpecialty(Specialty specialty) {
        getSpecialtiesInternal().add(specialty);
    }

}

containerbank3/src/main/java/org/hackathon/packapp/containerbank/model/Advisors.java
package org.hackathon.packapp.containerbank.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Simple domain object representing a list of advisors. Mostly here to be used for the 'advisors' {@link
 * org.springframework.web.servlet.view.xml.MarshallingView}.
 *
 * @author Wavestone
 */
@XmlRootElement
public class Advisors {

    private List<Advisor> advisors;

    @XmlElement
    public List<Advisor> getAdvisorList() {
        if (advisors == null) {
            advisors = new ArrayList<>();
        }
        return advisors;
    }

}

containerbank3/src/main/java/org/hackathon/packapp/containerbank/model/Card.java
package org.hackathon.packapp.containerbank.model;

import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;
import org.springframework.format.annotation.DateTimeFormat;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Simple business object representing a card.
 *
 * @author Wavestone
 */
@Entity
@Table(name = "cards")
public class Card extends NamedEntity {

    @Column(name = "birth_date")
    @DateTimeFormat(pattern = "yyyy/MM/dd")
    private LocalDate birthDate;

    @ManyToOne
    @JoinColumn(name = "type_id")
    private CardType type;

    @ManyToOne
    @JoinColumn(name = "customer_id")
    private Customer customer;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "card", fetch = FetchType.EAGER)
    private Set<Payment> payments;


    public void setBirthDate(LocalDate birthDate) {
        this.birthDate = birthDate;
    }

    public LocalDate getBirthDate() {
        return this.birthDate;
    }

    public CardType getType() {
        return this.type;
    }

    public void setType(CardType type) {
        this.type = type;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    protected void setCustomer(Customer customer) {
        this.customer = customer;
    }

    protected Set<Payment> getPaymentsInternal() {
        if (this.payments == null) {
            this.payments = new HashSet<>();
        }
        return this.payments;
    }

    protected void setPaymentsInternal(Set<Payment> payments) {
        this.payments = payments;
    }

    public List<Payment> getPayments() {
        List<Payment> sortedPayments = new ArrayList<>(getPaymentsInternal());
        PropertyComparator.sort(sortedPayments, new MutableSortDefinition("date", false, false));
        return Collections.unmodifiableList(sortedPayments);
    }

    public void addPayment(Payment payment) {
        getPaymentsInternal().add(payment);
        payment.setCard(this);
    }

}

containerbank3/src/main/java/org/hackathon/packapp/containerbank/model/CardType.java
package org.hackathon.packapp.containerbank.model;

import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * @author Wavestone
 */
@Entity
@Table(name = "types")
public class CardType extends NamedEntity {

}

containerbank3/src/main/java/org/hackathon/packapp/containerbank/web/CardController.java
package org.hackathon.packapp.containerbank.web;

import org.springframework.beans.factory.annotation.Autowired;
import org.hackathon.packapp.containerbank.model.Customer;
import org.hackathon.packapp.containerbank.model.Card;
import org.hackathon.packapp.containerbank.model.CardType;
import org.hackathon.packapp.containerbank.service.BankService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.util.StringUtils;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.WebDataBinder;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

import java.util.Collection;

/**
 * @author Wavestone
 */
@Controller
@RequestMapping("/customers/{customerId}")
public class CardController {

    private static final String VIEWS_cards_CREATE_OR_UPDATE_FORM = "cards/createOrUpdateCardForm";
    private final BankService bankService;

    @Autowired
    public CardController(BankService bankService) {
        this.bankService = bankService;
    }

    @ModelAttribute("types")
    public Collection<CardType> populateCardTypes() {
        return this.bankService.findCardTypes();
    }

    @ModelAttribute("customer")
    public Customer findCustomer(@PathVariable("customerId") int customerId) {
        return this.bankService.findCustomerById(customerId);
    }

    @InitBinder("customer")
    public void initCustomerBinder(WebDataBinder dataBinder) {
        dataBinder.setDisallowedFields("id");
    }

    @InitBinder("card")
    public void initCardBinder(WebDataBinder dataBinder) {
        dataBinder.setValidator(new CardValidator());
    }

    @RequestMapping(value = "/cards/new", method = RequestMethod.GET)
    public String initCreationForm(Customer customer, ModelMap model) {
        Card card = new Card();
        customer.addCard(card);
        model.put("card", card);
        return VIEWS_cards_CREATE_OR_UPDATE_FORM;
    }

    @RequestMapping(value = "/cards/new", method = RequestMethod.POST)
    public String processCreationForm(Customer customer, @Valid Card card, BindingResult result, ModelMap model) {
        if (StringUtils.hasLength(card.getName()) && card.isNew() && customer.getCard(card.getName(), true) != null){
            result.rejectValue("name", "duplicate", "already exists");
        }
        if (result.hasErrors()) {
            model.put("card", card);
            return VIEWS_cards_CREATE_OR_UPDATE_FORM;
        } else {
            customer.addCard(card);
            this.bankService.saveCard(card);
            return "redirect:/customers/{customerId}";
        }
    }

    @RequestMapping(value = "/cards/{cardId}/edit", method = RequestMethod.GET)
    public String initUpdateForm(@PathVariable("cardId") int cardId, ModelMap model) {
        Card card = this.bankService.findCardById(cardId);
        model.put("card", card);
        return VIEWS_cards_CREATE_OR_UPDATE_FORM;
    }

    @RequestMapping(value = "/cards/{cardId}/edit", method = RequestMethod.POST)
    public String processUpdateForm(@Valid Card card, BindingResult result, Customer customer, ModelMap model) {
        if (result.hasErrors()) {
            model.put("card", card);
            return VIEWS_cards_CREATE_OR_UPDATE_FORM;
        } else {
            customer.addCard(card);
            this.bankService.saveCard(card);
            return "redirect:/customers/{customerId}";
        }
    }

}

containerbank3/src/main/webapp/WEB-INF/jsp/cards/advisorsList.jsp
<%@ page session="false" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="containerbank" tagdir="/WEB-INF/tags" %>

<containerbank:layout pageName="advisors">
    <h2>Advisors</h2>

    <table id="advisorsTable" class="table table-striped">
        <thead>
        <tr>
            <th>Name</th>
            <th>Specialties</th>
        </tr>
        </thead>
        <tbody>
        <c:forEach items="${advisors.advisorList}" var="advisor">
            <tr>
                <td>
                    <c:out value="${advisor.firstName} ${advisor.lastName}"/>
                </td>
                <td>
                    <c:forEach var="specialty" items="${advisor.specialties}">
                        <c:out value="${specialty.name} "/>
                    </c:forEach>
                    <c:if test="${advisor.nrOfSpecialties == 0}">none</c:if>
                </td>
            </tr>
        </c:forEach>
        </tbody>
    </table>

    <table class="table-buttons">
        <tr>
            <td>
                <a href="<spring:url value="/advisors.xml" htmlEscape="true" />">View as XML</a>
            </td>
            <td>
                <a href="<spring:url value="/advisors.json" htmlEscape="true" />">View as JSON</a>
            </td>
        </tr>
    </table>
</containerbank:layout>

containerbank3/src/main/webapp/WEB-INF/jsp/cards/createOrUpdateCardForm.jsp
<%@ page session="false" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="containerbank" tagdir="/WEB-INF/tags" %>

<containerbank:layout pageName="customers">
    <jsp:attribute name="customScript">
        <script>
            $(function () {
                $("#birthDate").datepicker({dateFormat: 'yy/mm/dd'});
            });
        </script>
    </jsp:attribute>
    <jsp:body>
        <h2>
            <c:if test="${card['new']}">New </c:if> Card
        </h2>
        <form:form modelAttribute="card"
                   class="form-horizontal">
            <input type="hidden" name="id" value="${card.id}"/>
            <div class="form-group has-feedback">
                <div class="form-group">
                    <label class="col-sm-2 control-label">Customer</label>
                    <div class="col-sm-10">
                        <c:out value="${card.customer.firstName} ${card.customer.lastName}"/>
                    </div>
                </div>
                <containerbank:inputField label="Name" name="name"/>
                <containerbank:inputField label="Birth Date" name="birthDate"/>
                <div class="control-group">
                    <containerbank:selectField name="type" label="Type " names="${types}" size="5"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <c:choose>
                        <c:when test="${card['new']}">
                            <button class="btn btn-default" type="submit">Add Card</button>
                        </c:when>
                        <c:otherwise>
                            <button class="btn btn-default" type="submit">Update Card</button>
                        </c:otherwise>
                    </c:choose>
                </div>
            </div>
        </form:form>
        <c:if test="${!card['new']}">
        </c:if>
    </jsp:body>
</containerbank:layout>

containerbank3/src/main/webapp/WEB-INF/jsp/cards/createOrUpdatePaymentForm.jsp
<%@ page session="false" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="containerbank" tagdir="/WEB-INF/tags" %>


<containerbank:layout pageName="customers">
    <jsp:attribute name="customScript">
        <script>
            $(function () {
                $("#date").datepicker({dateFormat: 'yy/mm/dd'});
            });
        </script>
    </jsp:attribute>
    <jsp:body>
        <h2><c:if test="${payment['new']}">New </c:if>Payment</h2>

        <b>Card</b>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Name</th>
                <th>Birth Date</th>
                <th>Type</th>
                <th>Customer</th>
            </tr>
            </thead>
            <tr>
                <td><c:out value="${payment.card.name}"/></td>
                <td><containerbank:localDate date="${payment.card.birthDate}" pattern="yyyy/MM/dd"/></td>
                <td><c:out value="${payment.card.type.name}"/></td>
                <td><c:out value="${payment.card.customer.firstName} ${payment.card.customer.lastName}"/></td>
            </tr>
        </table>

        <form:form modelAttribute="payment" class="form-horizontal">
            <div class="form-group has-feedback">
                <containerbank:inputField label="Date" name="date"/>
                <containerbank:inputField label="Description" name="description"/>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <input type="hidden" name="cardId" value="${payment.card.id}"/>
                    <button class="btn btn-default" type="submit">Add Payment</button>
                </div>
            </div>
        </form:form>

        <br/>
        <b>Previous Payments</b>
        <table class="table table-striped">
            <tr>
                <th>Date</th>
                <th>Description</th>
            </tr>
            <c:forEach var="payment" items="${payment.card.payments}">
                <c:if test="${!payment['new']}">
                    <tr>
                        <td><containerbank:localDate date="${payment.date}" pattern="yyyy/MM/dd"/></td>
                        <td><c:out value="${payment.description}"/></td>
                    </tr>
                </c:if>
            </c:forEach>
        </table>
    </jsp:body>

</containerbank:layout>